[splits]
# where the number is the percentage of the data used for testing
data_splits_100=[
    "LPS_1.000_ug_per_ml_DMSO_0.025_%",
    "LPS_Nigericin_1.000_ug_per_ml_3.000_uM_DMSO_0.025_%",
    'Flagellin_0.100_ug_per_ml_DMSO_0.025_%',
    'Flagellin_1.000_ug_per_ml_DMSO_0.025_%',
    'Flagellin_1.000_ug_per_ml_Disulfiram_1.000_uM',
    ]
data_splits_75=[
    "LPS_0.010_ug_per_ml_DMSO_0.025_%",
    "LPS_100.000_ug_per_ml_DMSO_0.025_%"
    ]
