[DEFAULT]
DATA_SUBSET_OPTION = "True"
DATA_SUBSET_NUMBER = 500
BATCH_SIZE = 250
TRAIN_PROPORTION_SPLIT = 0.8
VALIDATION_PROPORTION_SPLIT = 0.1
TEST_PROPORTION_SPLIT = 0.1
OPTIM_EPOCHS = 50
N_TRIALS = 1
TRAIN_EPOCHS = 1000
MIN_LAYERS = 1
MAX_LAYERS = 3
LAYER_UNITS_MIN = 2
LAYER_UNITS_MAX = 10
DROPOUT_MIN = 0.1
DROPOUT_MAX = 0.4
DROP_OUT_STEP = 0.05
LEARNING_RATE_MIN = 1e-5
LEARNING_RATE_MAX = 0.1
OPTIMIZER_LIST = [ "Adam", "RMSprop", "SGD" ]
METRIC = "accuracy"
DIRECTION = "maximize"

